### ISSUE TITLE
XLN DFC Flavor Text is Doubled

### ISSUE THREAD

**Issue by jhallbachner** [scryfall/feedback#428]
I assume this is a Gatherer issue. It can be seen on, e.g. https://scryfall.com/card/xln/90 It does not appear to affect any previous sets with DFCs.

**Comment by doppeldeveloper** [comment]
This looks like it's limited to the Ixalan cards, and it wasn't like this a couple of weeks ago.

**Comment by josephprice** [comment]
Flavor Text now corrected. But keeping ticket open in case we need to inspect code to prevent from occurring again.

Here's what was appearing for the record:
![__e_xln_is_double-sided_ _scryfall_magic_card_search](https://user-images.githubusercontent.com/1693480/31100897-369dd4a0-a799-11e7-846b-7cb6b210740f.png)

![__e_xln_is_double-sided_ _scryfall_magic_card_search](https://user-images.githubusercontent.com/1693480/31100865-1a2e9a2a-a799-11e7-9034-dbd9bab33bbd.png)

**Comment by tooomm** [comment]
Interesting that for `Legion's Landing`, just the part in quotes is duplicated, not all flavor text...

**Comment by josephprice** [comment]
🤔🤔🤔🤔

**Comment by chuckharmston** [comment]
This was a bug in how we merged display of MFCs; I'm pretty confident in closing this issue.

**Comment by tooomm** [comment]
@chuckharmston while it's no longer displayed doubled for https://scryfall.com/card/xln/90 and https://scryfall.com/card/xln/74.
It's still wrong for https://scryfall.com/card/xln/22 in the same weird fashion as mentioned [above](https://github.com/scryfall/feedback/issues/428#issuecomment-334133256), even after a forced fresh reload! Also tried a different browser.

Didn't check on other dfc or mfc cards.

**Comment by josephprice** [comment]
I thought I fixed all of the issues, but apparently not. Corrected. Doesn't seem to be systematic.
