### ISSUE TITLE
Card rarities incorrect in early box sets

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#672]
ATH, ITP, and RQS have all non-basic cards at rare, instead of their true rarities. Rarities are correct in, say, BRB.

**Comment by csuhta** [comment]
ATH has been corrected, I added a tracker to your comment 😄

**Comment by NilsEnevoldsen** [comment]
What source did you use for the ATH corrections? I think Jalum Tome and Mirri, Cat Warrior are rares, but you still have them as uncommons.

**Comment by NilsEnevoldsen** [comment]
These might be canonical:

http://www.wizards.com/magic/displaythemedeck.asp?set=anthologies&decknum=1&lang=en

http://www.wizards.com/magic/displaythemedeck.asp?set=anthologies&decknum=2&lang=en
